name: umx-gpu

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python>=3.7
  - numpy>=1.18
  - scipy>=1.4
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - scikit-learn>=0.22
  - tqdm
  - libsndfile
  - soundfile
  - pip
  - pip:
    - ffmpeg
    - stempeg
    - musdb>=0.4.0
    - museval>=0.4.0
    - asteroid-filterbanks>=0.3.2
    - gitpython

